PROCESS BEFORE OUTPUT.

 MODULE STATUS_0100.
** 버튼 툴바 / 타이틀바 출력
 MODULE SET_ALV_0100.
** 필드카탈로그 / 레이아웃 / 펑션 alv 출력
PROCESS AFTER INPUT.

 MODULE USER_COMMAND_0100.
 MODULE SAVE_DATA.
 MODULE EDIT_DATA.
